spring.application.name=auth-service

server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/auth_db
spring.datasource.username=postgres
spring.datasource.password=YOUR_PASSWORD

spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=validate
#spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

jwt.secret=your-very-secret-key-with-at-least-32-characters