spring.application.name=api-gateway

server.port=8080

spring.main.web-application-type=reactive

spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=${AUTH_SERVICE_URL}
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**

spring.cloud.gateway.routes[1].id=audit-service
spring.cloud.gateway.routes[1].uri=${AUDIT_SERVICE_URL}
spring.cloud.gateway.routes[1].predicates[0]=Path=/audit/**,/ingest/audit/**

spring.cloud.gateway.routes[2].id=security-service
spring.cloud.gateway.routes[2].uri=${SECURITY_SERVICE_URL}
spring.cloud.gateway.routes[2].predicates[0]=Path=/security/**,/ingest/security/**

jwt.secret=${JWT_SECRET}

spring.webflux.cors.allowed-origins=${FRONTEND_URL}
spring.webflux.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.webflux.cors.allowed-headers=*
spring.webflux.cors.allow-credentials=true
