spring.application.name=agent-service
server.port=9090

smtap.audit.url=http://localhost:8080/audit/events

agent.log.path=A:/ravi/projects/smtap-microservices/logs/application.log


agent.api-key=9207c02c-4537-4ae9-bb59-f7587e6f416e

agent.actor-id=finance-backend
